theme: jekyll-theme-minimal
title: Kumar Prakhar
description: Sophomore at VIT Bhopal University, pursuing B. Tech in Computer Science Engineering with specialization in Artificial Intelligence and Machine Learning, aiming to leverage my abilities to complete different projects in the field of Data Science. Ready for on job training to improve my skills and gain valuable work experience. Frequently praised as detail-oriented by my peers, I can be relied upon to help your company achieve its goals.
logo: /assets/img/logo.jpg
show_downloads: false